server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  show-sql: true

  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    open-in-view: false  # 뷰 렌더링 중에 데이터베이스 연결이 필요하지 않은 경우에는 비효율적일 수 있습

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/${data}?serverTimezone=Asia/Seoul
    username: ${name}
    password: ${pw}

  sql.init.mode: always

  jwt:
    secret-key: ${key}

  servlet:
    multipart:
      max-file-size: 20MB         # 파일 업로드 최대 크기
      max-request-size: 20MB


ImgLocation: C:/file/upload/    # 상품 이미지 저장 위치
uploadPath: file:///C:/upload/      # 상품 이미지 업로드 위치


logging:
  level:
    org.hibernate.SQL: DEBUG               # SQL 쿼리 로그를 출력
    org.hibernate.type.descriptor.sql.BasicTypeDescriptor: TRACE # 바인딩된 파라미터의 로그를 출력


kakao:
  map:
    api:
      url: https://dapi.kakao.com/v2/local/search/address.json
      key: ${kakoapikey}

